### PR TITLE
Kkotorov/redesign

### PR DESCRIPTION
**Pull request by Mike4o**

### CODE REVIEW

**Comment by teobugslayer** [comment]
Tested on two Android devices - both consistently point to East as being South - is it possible that we are reading the device sensor information incorrectly?

**Comment by teobugslayer** [comment]
:+1:

**Comment by didiepetrova** [comment]
Nice! Only ReadMe.md "Try in Platform" -> 'Try in the Platform'

**Comment by TsvetinaIvanova** [comment]
Not a must but you can re-take the screenshot with the Console closed, so that it doesn't output the device screen in the upper right corner of the screenshot.

**Comment by didiepetrova** [comment]
:+1: p.s. There is a small hover on the top right of the screenshot. The ReadMe.md could be updated to explain what is the difference between pressing the "Start Compass" or "Orientation" buttons.

**Pull request merged**
